//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HijackGen.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GUIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GUIStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HijackGen.Strings.GUIStrings", typeof(GUIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string BtCancel {
            get {
                return ResourceManager.GetString("BtCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate 的本地化字符串。
        /// </summary>
        public static string BtGenerate {
            get {
                return ResourceManager.GetString("BtGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VS Solution 的本地化字符串。
        /// </summary>
        public static string BtVSSolution {
            get {
                return ResourceManager.GetString("BtVSSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Address 的本地化字符串。
        /// </summary>
        public static string ClmAddress {
            get {
                return ResourceManager.GetString("ClmAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dll Name 的本地化字符串。
        /// </summary>
        public static string ClmDllName {
            get {
                return ResourceManager.GetString("ClmDllName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Forward Name 的本地化字符串。
        /// </summary>
        public static string ClmForwardName {
            get {
                return ResourceManager.GetString("ClmForwardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Has Forward 的本地化字符串。
        /// </summary>
        public static string ClmHasForward {
            get {
                return ResourceManager.GetString("ClmHasForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hint 的本地化字符串。
        /// </summary>
        public static string ClmHint {
            get {
                return ResourceManager.GetString("ClmHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IAT Offset 的本地化字符串。
        /// </summary>
        public static string ClmIATOffset {
            get {
                return ResourceManager.GetString("ClmIATOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string ClmName {
            get {
                return ResourceManager.GetString("ClmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ordinal 的本地化字符串。
        /// </summary>
        public static string ClmOrdinal {
            get {
                return ResourceManager.GetString("ClmOrdinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string MnAbout {
            get {
                return ResourceManager.GetString("MnAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plugins 的本地化字符串。
        /// </summary>
        public static string MnPlugins {
            get {
                return ResourceManager.GetString("MnPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Demonstrate the import table of a PE file. 的本地化字符串。
        /// </summary>
        public static string PluginDescImportChecker {
            get {
                return ResourceManager.GetString("PluginDescImportChecker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open regedit to check KnownDlls. 的本地化字符串。
        /// </summary>
        public static string PluginDescKnownDllsChecker {
            get {
                return ResourceManager.GetString("PluginDescKnownDllsChecker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check Import 的本地化字符串。
        /// </summary>
        public static string PluginNameImportChecker {
            get {
                return ResourceManager.GetString("PluginNameImportChecker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check KnownDlls 的本地化字符串。
        /// </summary>
        public static string PluginNameKnownDllsChecker {
            get {
                return ResourceManager.GetString("PluginNameKnownDllsChecker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Architecture 的本地化字符串。
        /// </summary>
        public static string TxtArchitecture {
            get {
                return ResourceManager.GetString("TxtArchitecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom Dll 的本地化字符串。
        /// </summary>
        public static string TxtCustomDll {
            get {
                return ResourceManager.GetString("TxtCustomDll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Development Site 的本地化字符串。
        /// </summary>
        public static string TxtDevSite {
            get {
                return ResourceManager.GetString("TxtDevSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dll Path 的本地化字符串。
        /// </summary>
        public static string TxtDllPath {
            get {
                return ResourceManager.GetString("TxtDllPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dll Type 的本地化字符串。
        /// </summary>
        public static string TxtDllType {
            get {
                return ResourceManager.GetString("TxtDllType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output File Format 的本地化字符串。
        /// </summary>
        public static string TxtOutputFormat {
            get {
                return ResourceManager.GetString("TxtOutputFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PE Path 的本地化字符串。
        /// </summary>
        public static string TxtPEPath {
            get {
                return ResourceManager.GetString("TxtPEPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Path 的本地化字符串。
        /// </summary>
        public static string TxtSavePath {
            get {
                return ResourceManager.GetString("TxtSavePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Dll 的本地化字符串。
        /// </summary>
        public static string TxtSystemDll {
            get {
                return ResourceManager.GetString("TxtSystemDll", resourceCulture);
            }
        }
    }
}
