//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HijackGen.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GuiStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GuiStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HijackGen.Strings.GuiStrings", typeof(GuiStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Address 的本地化字符串。
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All Files 的本地化字符串。
        /// </summary>
        public static string AllFilesFilter {
            get {
                return ResourceManager.GetString("AllFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Architecture 的本地化字符串。
        /// </summary>
        public static string Architecture {
            get {
                return ResourceManager.GetString("Architecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check KnownDlls 的本地化字符串。
        /// </summary>
        public static string CheckKnownDlls {
            get {
                return ResourceManager.GetString("CheckKnownDlls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom Dll 的本地化字符串。
        /// </summary>
        public static string CustomDll {
            get {
                return ResourceManager.GetString("CustomDll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dll Name 的本地化字符串。
        /// </summary>
        public static string DllName {
            get {
                return ResourceManager.GetString("DllName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dll Type 的本地化字符串。
        /// </summary>
        public static string DllType {
            get {
                return ResourceManager.GetString("DllType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Count 的本地化字符串。
        /// </summary>
        public static string ExportCount {
            get {
                return ResourceManager.GetString("ExportCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Info 的本地化字符串。
        /// </summary>
        public static string ExportInfos {
            get {
                return ResourceManager.GetString("ExportInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Forward Name 的本地化字符串。
        /// </summary>
        public static string ForwardName {
            get {
                return ResourceManager.GetString("ForwardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate 的本地化字符串。
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Has Forward 的本地化字符串。
        /// </summary>
        public static string HasForward {
            get {
                return ResourceManager.GetString("HasForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hint 的本地化字符串。
        /// </summary>
        public static string Hint {
            get {
                return ResourceManager.GetString("Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IAT Offset 的本地化字符串。
        /// </summary>
        public static string IATOffset {
            get {
                return ResourceManager.GetString("IATOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import Count 的本地化字符串。
        /// </summary>
        public static string ImportCount {
            get {
                return ResourceManager.GetString("ImportCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import Info 的本地化字符串。
        /// </summary>
        public static string ImportInfos {
            get {
                return ResourceManager.GetString("ImportInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Options 的本地化字符串。
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ordinal 的本地化字符串。
        /// </summary>
        public static string Ordinal {
            get {
                return ResourceManager.GetString("Ordinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output File Format 的本地化字符串。
        /// </summary>
        public static string OutputFormat {
            get {
                return ResourceManager.GetString("OutputFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path 的本地化字符串。
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PE Files 的本地化字符串。
        /// </summary>
        public static string PeFilter {
            get {
                return ResourceManager.GetString("PeFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PE Info 的本地化字符串。
        /// </summary>
        public static string PeInfo {
            get {
                return ResourceManager.GetString("PeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Path 的本地化字符串。
        /// </summary>
        public static string SavePath {
            get {
                return ResourceManager.GetString("SavePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source URL 的本地化字符串。
        /// </summary>
        public static string SourceUrl {
            get {
                return ResourceManager.GetString("SourceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Dll 的本地化字符串。
        /// </summary>
        public static string SystemDll {
            get {
                return ResourceManager.GetString("SystemDll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tools 的本地化字符串。
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
    }
}
