//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HijackGen.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HijackGen.Strings.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Attention: Some exported function names contain invalid characters, which may cause the generated .h file to be invalid. 的本地化字符串。
        /// </summary>
        public static string msgContainsInvalidChars {
            get {
                return ResourceManager.GetString("msgContainsInvalidChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} exported functions found. 的本地化字符串。
        /// </summary>
        public static string msgExportFound {
            get {
                return ResourceManager.GetString("msgExportFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to save: {0} 的本地化字符串。
        /// </summary>
        public static string msgFailedWithMsg {
            get {
                return ResourceManager.GetString("msgFailedWithMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid PE file. 的本地化字符串。
        /// </summary>
        public static string msgInvalidPE {
            get {
                return ResourceManager.GetString("msgInvalidPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid dll: {0} 的本地化字符串。
        /// </summary>
        public static string msgNotDll {
            get {
                return ResourceManager.GetString("msgNotDll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File not found or access denied: {0} 的本地化字符串。
        /// </summary>
        public static string msgNotFound {
            get {
                return ResourceManager.GetString("msgNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input dll path. 的本地化字符串。
        /// </summary>
        public static string msgPleaseInputPath {
            get {
                return ResourceManager.GetString("msgPleaseInputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plugin execution failed: {0} 的本地化字符串。
        /// </summary>
        public static string msgPluginError {
            get {
                return ResourceManager.GetString("msgPluginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ready 的本地化字符串。
        /// </summary>
        public static string msgReady {
            get {
                return ResourceManager.GetString("msgReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please specify save directory 的本地化字符串。
        /// </summary>
        public static string msgSpecifyPath {
            get {
                return ResourceManager.GetString("msgSpecifyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saved. 的本地化字符串。
        /// </summary>
        public static string msgSuccess {
            get {
                return ResourceManager.GetString("msgSuccess", resourceCulture);
            }
        }
    }
}
