//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HijackGen {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HijackGen.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 All Files 的本地化字符串。
        /// </summary>
        public static string msgAllFilesFilter {
            get {
                return ResourceManager.GetString("msgAllFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation canceled. 的本地化字符串。
        /// </summary>
        public static string msgCanceled {
            get {
                return ResourceManager.GetString("msgCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Some exported function names contain invalid characters, which may cause the generated .h file to be invalid. Do you want to continue? 的本地化字符串。
        /// </summary>
        public static string msgContainsInvalidChars {
            get {
                return ResourceManager.GetString("msgContainsInvalidChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path cannot be empty. 的本地化字符串。
        /// </summary>
        public static string msgEmpty {
            get {
                return ResourceManager.GetString("msgEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} exported functions found. 的本地化字符串。
        /// </summary>
        public static string msgExportFound {
            get {
                return ResourceManager.GetString("msgExportFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to save. 的本地化字符串。
        /// </summary>
        public static string msgFailed {
            get {
                return ResourceManager.GetString("msgFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to save: {0} 的本地化字符串。
        /// </summary>
        public static string msgFailedWithMsg {
            get {
                return ResourceManager.GetString("msgFailedWithMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} imported functions found. 的本地化字符串。
        /// </summary>
        public static string msgImportFound {
            get {
                return ResourceManager.GetString("msgImportFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown PE type: {0} 的本地化字符串。
        /// </summary>
        public static string msgNotDll {
            get {
                return ResourceManager.GetString("msgNotDll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File not found or access denied: {0} 的本地化字符串。
        /// </summary>
        public static string msgNotFound {
            get {
                return ResourceManager.GetString("msgNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DLL/EXE files 的本地化字符串。
        /// </summary>
        public static string msgPEFilter {
            get {
                return ResourceManager.GetString("msgPEFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ready 的本地化字符串。
        /// </summary>
        public static string msgReady {
            get {
                return ResourceManager.GetString("msgReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please specify output format. 的本地化字符串。
        /// </summary>
        public static string msgSpecifyFormat {
            get {
                return ResourceManager.GetString("msgSpecifyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please specify save directory 的本地化字符串。
        /// </summary>
        public static string msgSpecifyPath {
            get {
                return ResourceManager.GetString("msgSpecifyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saved. 的本地化字符串。
        /// </summary>
        public static string msgSuccess {
            get {
                return ResourceManager.GetString("msgSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        public static string msgWarning {
            get {
                return ResourceManager.GetString("msgWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Working… 的本地化字符串。
        /// </summary>
        public static string msgWorking {
            get {
                return ResourceManager.GetString("msgWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check KnownDlls 的本地化字符串。
        /// </summary>
        public static string ToolKnownDlls {
            get {
                return ResourceManager.GetString("ToolKnownDlls", resourceCulture);
            }
        }
    }
}
